version: '3'

services:
  postgres-master:
    image: postgres:latest
    container_name: postgres-master
    environment:
      POSTGRES_USER: master_user
      POSTGRES_PASSWORD: master_password
      POSTGRES_DB: i3
    volumes:
      - pg_master_data:/var/lib/postgresql/data
      - ./external/database/master/init:/docker-entrypoint-initdb.d
    networks:
      - weather-net
    ports:
      - "5432:5432"

  postgres-slave:
    image: postgres:latest
    container_name: postgres-slave
    environment:
      POSTGRES_USER: replica_user
      POSTGRES_PASSWORD: replica_password
      POSTGRES_DB: i3
      REPLICATE_FROM: postgres-master
    volumes:
      - pg_slave_data:/var/lib/postgresql/data
      - ./external/database/slave/init:/docker-entrypoint-initdb.d
    networks:
      - weather-net
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master

  redis:
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./external/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - weather-net

  api-gateway:
    image: nginx:alpine
    volumes:
      - ./external/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - weather-net


  backend:
    build: 
      context: .
    container_name: backend-server
    ports:
      - "9000:9000"
    networks:
      - weather-net
    depends_on:
      - postgres-master
      - postgres-slave
      - redis

volumes:
  pg_master_data:
  pg_slave_data:

networks:
  weather-net:
    driver: bridge
